### ISSUE TITLE
Make card prettier

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Website#14]
Take for example https://catima.app/share/#store%3DExample%26note%3D%26balance%3D0%26cardid%3D1234%26barcodetype%3DCODE_128%26headercolor%3D-1784274

This doesn't look nice:
![image](https://user-images.githubusercontent.com/1885159/191582496-63274991-1a2c-4cff-ac08-9dd173c5fff6.png)

How to make it pretty, I don't know, I'm not a designer :)

**Comment by LunarMarathon** [comment]
Hi, I would like to work on this, could you please assign it to me?

**Comment by TheLastProject** [comment]
Assigned it to you.

If it helps the design, https://catimaloyalty.readthedocs.io/en/latest/docs/card_sharing_url_format/ should list all the options you may possibly run into :)

**Comment by TheLastProject** [comment]
Hey, I haven't heard from you for over a week. Are you still working on this?

**Comment by LunarMarathon** [comment]
Hey, I'm sorry, I haven't been able to work on it, have just been getting too many errors, last one being Ruby version mismatch. I'm new to ruby and jekyll and still need to look up on installing rvm on windows. Please assign it to someone else if needed

**Comment by TheLastProject** [comment]
Jekyll really can be a pain sometimes on some systems yeah. You can also bypass the whole building part by just making a PR, because Netlify will automatically build each commit. Of course, that does make stuff a lot slower as you can't just refresh your browser but will have to push each try to GitHub, wait for Netlify to complete, and follow the URL it generated

**Comment by andreasgrafen** [comment]
Heya, as this got unassigned I wanted to ask if this is open to work on? I have an idea or two on how this potentially could be improved and if it's needed I'd give it a shot. c:

**Comment by TheLastProject** [comment]
Sure, would love to see what you come up with :)

**Comment by TheLastProject** [comment]
Oh, that looks really nice and readable and will fit really well on a smartphone screen!

> The background colour is taken from the logo itself. In theory the background colour could even be customisable per card.

Yeah re-using the card background colour like that would be great, although making sure the font stays readable could become a challenge.

> One issue I have with this as of right now is the subtle drop shadow I used to differentiate the white background of the barcode from the page background itself as there are no dropshadows anywhere else on the page.

In what way are you having an issue with it? It looks quite fine to me.

> I'm not super familiar with barcode, but I'd assume that the background colour has to be pure white, right?

While some barcode types allow reverting colours (but not all) I've noticed many scanners and the likes do have trouble with it. That's why Catima always uses a white background in-app. So I think keeping that would definitely be a good idea.

**Comment by andreasgrafen** [comment]
> Oh, that looks really nice and readable and will fit really well on a smartphone screen!

Yeah, that's the idea. It's unlikely someone would watch this on a desktop device, right?
&nbsp;

> although making sure the font stays readable could become a challenge.

One would likely need to introduce some Javascript to check the contrast and chose either black or white text based on that. Alternatively it could also just be generated from a given array of possible colours that are tested to play well with either white or black text.
&nbsp;

> In what way are you having an issue with it? It looks quite fine to me.

Regarding the drop-shadow it's just that introduced a style that is completely forgein to the rest of the site. It's not bad or anything, but it def. makes this element stand out more – and I'm not sure if that's necessarily a good thing. But for this kind of layout it's prob. the best way to avoid the background bleeding into the card.
I thought about the possibility of the barcode background being the same grey that is used for the icon background, but judging by your reply that's not an option. o:

**Comment by andreasgrafen** [comment]
I have drafted a PR to make the changes available live as well. The default data lacks the expiration date and description tho.

**Comment by TheLastProject** [comment]
> Yeah, that's the idea. It's unlikely someone would watch this on a desktop device, right?

Unlikely, but possible. It looks just fine on desktop too though, but mobile is definitely the primary concern.

> One would likely need to introduce some Javascript to check the contrast and chose either black or white text based on that. Alternatively it could also just be generated from a given array of possible colours that are tested to play well with either white or black text.

We need JavaScript already just to read the card data from the URL (so it is never sent to the server for privacy reasons), so adding a bit more isn't a problem at all.

> Regarding the drop-shadow it's just that introduced a style that is completely forgein to the rest of the site. It's not bad or anything, but it def. makes this element stand out more – and I'm not sure if that's necessarily a good thing. But for this kind of layout it's prob. the best way to avoid the background bleeding into the card.

Well, I'm not a designer so I can't really tell anything more than that I think it looks really good :)

> I have drafted a PR to make the changes available live as well.

Thanks! It's nice to be able to look at the progress so far :)

> The default data lacks the expiration date and description tho.

Good catch, I've created https://catima.app/share/#store%3DTest%2Bname%26note%3DTest%2Bnote%26balance%3D13.37%26balancetype%3DEUR%26expiry%3D1665525600000%26cardid%3DTest%2BID%26barcodetype%3DCODE_128%26headercolor%3D-14137216 with pretty much every field filled in from the app, can confirm it also looks really good on your design. Just missing the card colour part (which is often used by people to recognize a card as they often use the same colour as the brand in question's primary colour)

**Comment by andreasgrafen** [comment]
That begs the question: How is the card colour communicated to the frontend? Is the `headercolor` parameter in the URL the encoded colour to be used, or would there be the need to add something for that?
Adding on a contrast checker and then set both the background and text colour should be fairly straight forward then. c:

**Comment by TheLastProject** [comment]
Indeed, see https://catimaloyalty.readthedocs.io/en/latest/docs/card_sharing_url_format/. It's sadly an Android color value though, which is... not super easy: https://developer.android.com/reference/android/graphics/Color.

In the link in question, the value is `-14137216`, but I'm not quite sure how to make sense of that in JavaScript. In the Android app it is a darker blue:

**Comment by andreasgrafen** [comment]
hmm… okay. I've tried to research a little bit and I came across this website, but it returns a completely different colour as to what it should be. That just makes me even more unsure how to make this happen. But I'm fairly certain there is a solution to convert that value to HEX or RGB in JS – the internet wouldn't be the internet if that would not exist. :D

**Comment by andreasgrafen** [comment]
Okay, so in theory this code *should* work for this usecase. It's not super flexible, but it works within the given boundaries. https://jsfiddle.net/qa26wbd0/ – as to put this into action; is there a preferred way to introduce JS to the site? I'm asking since currently there only seems to be one JS file, and that is a library, right?

**Comment by TheLastProject** [comment]
That looks awesome! Thank you so much :)

Currently I've put the Javacript in https://github.com/CatimaLoyalty/Website/blob/master/_pages/share.md?plain=1 but as you may have noticed from the not-very-amazing code quality I'm not a web dev at all and am not up-to-date with modern best-practices. Given you do a lot more JavaScript than me judging from your profile I'll trust your judgment on what organization method looks best. My main concern is that having things locally is generally better than on some CDN because it avoids introducing another point of failure and privacy leaks.
