### ISSUE TITLE
Top menu in dropdown on mobile

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Website#15]
The top menu entries: `What's New, FAQ, Source Code` are currently hidden on mobile because they caused horizontal scrolling. They should become part of some drop-down menu probably. Or whatever works and feels good.

**Comment by gaurav-iitb** [comment]
I can help you with that can you please assign this to me

**Comment by TheLastProject** [comment]
Assigned you, thank you for taking a look into this :)

**Comment by gaurav-iitb** [comment]
can you please help me with how to run this website in our local computer

**Comment by TheLastProject** [comment]
I suppose the instructions in https://github.com/CatimaLoyalty/Website#how-to-build don't work given you're asking?

It's a pretty basic Jekyll site so it should be similar to this: https://jekyllrb.com/docs/ (maybe the README needs updating)

**Comment by TheLastProject** [comment]
I haven't heard from you since you brought up your problems. Are you still working on this?

**Comment by gaurav-iitb** [comment]
hi sorry I have been fixing the issue actually the Jekyll is not installing in my Mac m1 . So that's why I am working on it within two days I will update the pr
