### ISSUE TITLE
Donation page

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Website#16]
Because why not, Catima is a lot of work and I'm still paying money to keep the domain name and stuff up :) It's okay for a hobby to cost money, but it'd be better if Catima would stand on its own :)

**Comment by gaurav-iitb** [comment]
hi @TheLastProject  I would like to work on this as a part of hacktoberfest please provide me more info what all things you require in this

**Comment by TheLastProject** [comment]
Hey @gaurav-iitb

This will need:
1. A new page (`/donate`) with an explanation about accepting donations, linking to GitHub Sponsors (https://github.com/sponsors/TheLastProject) and PayPal (https://www.paypal.com/paypalme/sylviavanos)
2. A donate link in the website header and footer
3. The "Do you accept donations?" from the FAQ can be removed.

For the donate page, I quite like the way [KISS](https://help.kisslauncher.com/donate/) does it as they make very clear that donations are completely optional.

The main thing that is different is the "How will your money be used?" part. While Catima also has very little costs (currently only the catima.app domain), Catima also doesn't have any third-party contributors who want to be paid (yet? who knows what the future brings) and it definitely doesn't relate to third-world country stuff (although I do try to keep Catima lean-and-green and working well on old devices). Donations for Catima are more a "thank you" than anything else, so it would be important for people to not think that their money will be used to do something great (if we do ever get contributors in the future who want to be paid and will create good enough stuff that it's worth it, I can update the text myself)

**Comment by Tjs002** [comment]
@TheLastProject can I work on this?

**Comment by TheLastProject** [comment]
Sure :)
