### ISSUE TITLE
Set up robots.txt

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Website#21]
We need to exclude /share, Google indexed https://catima.app/share/ because some people running the Google Chrome spyware opened a share link.

**Comment by VirginieLemaire** [comment]
I'm realizing I never did a robots.txt 👀 and I'm interested in learning how to do this. Could I learn by contributing to this issue?

**Comment by TheLastProject** [comment]
Feel free to give it a try, we need `/share` not indexed by any search engine as the URL is useless by itself. The format is pretty well documented: https://www.robotstxt.org/robotstxt.html

**Comment by VirginieLemaire** [comment]
I have seen [this article](https://medium.com/@vilcins/optimize-your-jekyll-powered-website-with-these-simple-steps-b2a24d66a629) to ensure I put the robots.txt file in the good place in a jekyll project.

It's also talking about the [Jekyll SEO tag](https://github.com/jekyll/jekyll-seo-tag). Do you want me to add this in the same time ?

**Comment by TheLastProject** [comment]
I don't really have a lot of SEO knowledge so I can't really judge that well but you're free to experiment with the "Jekyll SEO tag" thing and explain your changes and why they're an improvement, but let's do that in another issue/MR then and first focus on robots.txt :)

**Comment by VirginieLemaire** [comment]
You're right, it's not exactly the same : focus ;)
