### ISSUE TITLE
Direct APK download button

### ISSUE THREAD

**Issue by TheLastProject** [CatimaLoyalty/Website#7]
We currently have a download button for Google Play and F-Droid.

It would be nice to have a direct APK download button that shows a dialog or page warning users that downloading like this means they won't get updates and that using Google Play or F-Droid is recommended, but linking to https://github.com/TheLastProject/Catima/releases/latest/download/app-release.apk if the user wants it anyway.

Probably should also offer a link to https://github.com/TheLastProject/Catima/releases/download/v2.6.1/app-release.apk for old devices, as it seems version 2.6.1 will likely be the last version supporting Android 4.4

**Comment by SurendarSingh** [comment]
Ok, I will do it

**Comment by SurendarSingh** [comment]
Hi @TheLastProject, The index.html is empty and I don't get any button tag where I can edit the code. Sorry maybe I don't know how to solve this issue
;)

**Comment by TheLastProject** [comment]
Ah, yeah, Jekyll has a bit of a weird structure.

You're looking for _layouts/default.html (and perhaps _pages/share.md).

It would be great if you could also add a variable to _config.yml: direct_download_link (or maybe direct_download_links so we can have something like `[{'https://...', 'main'}, {'https://...', 'Android 4.4'}]`)

**Comment by SurendarSingh** [comment]
Hey sorry, I could just figure out changing the link in the YAML file, but couldn't able to figure out other things. I'm really sorry, I'm not familiar with this language.
I should unassign myself

**Comment by lisztomania23** [comment]
assign this to me
i tried 😅: https://main--dashing-biscuit-2ef861.netlify.app/

**Comment by TheLastProject** [comment]
That's cool! The button looks good :) Feel free to make a merge request (although I did notice a bug, if you set your screensize to something like 996 width the button falls out of the screen, so that does need fixing, but it's a small thing)

**Comment by lisztomania23** [comment]
updated 👍 where do I make a pr, in the main?

**Comment by lisztomania23** [comment]
@TheLastProject hello i've made a PR do review it

**Comment by obfusk** [comment]
FWIW, I recently made an SVG badge for direct APK downloads for my own apps:

![Get the APK from GitHub](https://raw.githubusercontent.com/obfusk/misc/master/badges/gh-dl.png)

**Comment by TheLastProject** [comment]
Adding that to the website would be helpful. I'm thinking as last button (I prefer to prioritize the "stores" as they have updaters and thus users will get new versions automatically which they won't if they download from GitHub).

Do you want to do that yourself so the git commit history reflects that or shall I?

**Comment by obfusk** [comment]
If you like the button, I'm happy to make a PR. I was also thinking to put it last. I probably need to adjust the button slightly to match the dimensions of the others. Any other changes you want to request before I make the PR?

And do you still want to have some kind of warning about updates? I think linking to https://github.com/CatimaLoyalty/Android/releases/latest instead of directly to the APK makes the most sense. Would then be nice if we could have the warning there. But that would probably require copy-pasting it each time you make a new release, unless you're using some kind of template it could be added to? idk.

**Comment by TheLastProject** [comment]
The button looks fine to me.

Linking to releases/latest makes sense to me. I don't have a template, I don't know if GitHub supports something like that for releases, but putting some message there makes sense, I'll do that soon (makes more sense than putting it in the website as users may find the GitHub page in another method too)
